apiVersion: batch/v1
kind: Job
metadata:
  name: detlam-MEREPLACE
spec:
  completions: 20
  parallelism: 10
  template:
    spec:
      containers:
        - name: detlam-cont-MEREPLACE
          image: eu.gcr.io/vu-msc-thesis/vu-msc-thesis:gke
          command: ["bash", "scripts/determine_lambda_preliminary.sh", "REPLACEME"]
          resources: 
            requests:
              cpu: 1000m 
              memory: 1500Mi 
            limits:
              cpu: 1500m
              memory: 2000Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/out
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out
