apiVersion: batch/v1
kind: Job
metadata:
  name: modelfit-designb-t2000-p49
spec:
  completions: 50
  parallelism: 10
  template:
    spec:
      containers:
        - name: modelfit-cont-designb-t2000-p49
          image: eu.gcr.io/vu-msc-thesis/vu-msc-thesis:gke
          command: ["bash", "scripts/model_fit_montecarlo.sh", "designB_T2000_p49"]
          resources: 
            requests:
              cpu: 1500m 
              memory: 2000Mi 
            limits:
              cpu: 1500m
              memory: 2000Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/out
            - name: pv-data
              mountPath: /app/vu-msc-thesis/data
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out
        - name: pv-data
          persistentVolumeClaim:
            claimName: pvc-data