apiVersion: batch/v1
kind: Job
metadata:
  name: modelfit-MEREPLACE
spec:
  completions: 250
  parallelism: 25
  template:
    spec:
      containers:
        - name: modelfit-cont-MEREPLACE
          image: eu.gcr.io/vu-msc-thesis/vu-msc-thesis:gke
          command: ["bash", "scripts/model_fit_montecarlo.sh", "REPLACEME"]
          resources: 
            requests:
              cpu: 1000m 
              memory: 2000Mi 
            limits:
              cpu: 1500m
              memory: 2000Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/out
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out