apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcs-csi-rwx
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-out-gcs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: gcs-csi-rwx
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/vu-msc-thesis/zones/eu-west1-b/disks/thesisgke
    volumeAttributes:
      type: pd-standard

---

apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: pvc-out-gcs 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gcs-csi-rwx
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: data-access-gcs 
spec:
  containers:
  - name: data-access-gcs-container
    image: eu.gcr.io/vu-msc-thesis/vu-msc-thesis:gke 
    volumeMounts:
    - name: pv-out-gcs 
      mountPath: /app/vu-msc-thesis/out 
    resources:
      limits:
        cpu: 3000m 
        memory: 3000Mi
  volumes:
  - name: pv-out-gcs
    persistentVolumeClaim:
      claimName: pvc-out-gcs
