apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-out
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/eu-west1-b/filestore-thesis/sharedvol"
    volumeAttributes:
      ip: 10.18.142.114
      volume: sharedvol 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-out 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-out 
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: Pod
metadata:
  name: data-access
spec:
  containers:
  - name: data-access-cont
    image: eu.gcr.io/vu-msc-thesis/vu-msc-thesis:gke
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: pv-out
      mountPath: /app/vu-msc-thesis/out
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 500Mi
  volumes:
  - name: pv-out
    persistentVolumeClaim:
      claimName: pvc-out
