rho_seq <- exp(seq(-log(1e3),log(1e3),length.out=20))
load("../example_constant_rho_variantADMM.RData")
out.table_variantADMM <- out.table
load("../example_constant_rho.RData")
time_max = max(out.table[,1])
time_max_variantADMM = max(out.table_variantADMM[,1])
iter_max = max(out.table[,3])
iter_max_variantADMM = max(out.table_variantADMM[,3])

pdf("../../plots/constant_rho.pdf")
par(mfrow=c(2,2))
plot(log(rho_seq),out.table_variantADMM[,1],type="l",col="red",xlab="",ylab="",ylim=c(0,time_max_variantADMM))
mtext("time(s)",2,2)
mtext(expression(log(rho)),1,3)
mtext("augmented ADMM",3,1)
abline(h=52,col="blue")
legend(-2,time_max_variantADMM, c("constant penalty","adaptive penalty"), col = c("red","blue"), lty=c(1,1),bty="n",cex=.8)

plot(log(rho_seq),out.table[,1],type="l",col="red",xlab="",ylab="",ylim=c(0,time_max))
mtext("time(s)",2,2)
mtext(expression(log(rho)),1,3)
mtext("standard ADMM",3,1)
abline(h=309,col="blue")
legend(-2,time_max, c("constant penalty","adaptive penalty"), col = c("red","blue"), lty=c(1,1),bty="n",cex=.8)
# dev.off()

# pdf("ADMMiter_constant_rho.pdf")
#par(mfrow=c(1,2))
plot(log(rho_seq),log10(out.table_variantADMM[,3]),type="l",col="red",xlab="",ylab="",ylim=c(2,log10(iter_max_variantADMM)))
mtext(paste(expression(log),"(#iter)"),2,2)
mtext(expression(log(rho)),1,3)
mtext("augmented ADMM",3,1)
abline(h=log10(353),col="blue")
legend(-2,log10(iter_max_variantADMM), c("constant penalty","adaptive penalty"),
col = c("red","blue"), lty=c(1,1),bty="n",cex=.8)

plot(log(rho_seq),log10(out.table[,3]),type="l",col="red",xlab="",ylab="",ylim=c(2,log10(iter_max)))
mtext(paste(expression(log ),"(#iter)"),2,2)
mtext(expression(log(rho)),1,3)
mtext("standard ADMM",3,1)
abline(h=log10(247),col="blue")
legend(-2,log10(iter_max), c("constant penalty","adaptive penalty"), col = c("red","blue"), lty=c(1,1),bty="n",cex=.8)
dev.off()
