apiVersion: batch/v1
kind: Job
metadata:
  name: modelfit-designc-t500-p16
spec:
  completions: 100 
  parallelism: 3
  template:
    spec:
      containers:
        - name: modelfit-cont-designc-t500-p16
          image: jaccusaurelius/vu-msc-thesis:workspace
          command: ["bash", "scripts/model_fit_montecarlo.sh", "designC_T500_p16", "fullcv"]
          resources: 
            requests:
              cpu: 2000m 
              memory: 1500Mi 
            limits:
              cpu: 2500m
              memory: 1500Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/out
            - name: pv-data
              mountPath: /app/vu-msc-thesis/data
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out
        - name: pv-data
          persistentVolumeClaim:
            claimName: pvc-data