apiVersion: batch/v1
kind: Job
metadata:
  name: modelfit-designb-t1000-p36
spec:
  completions: 100
  parallelism: 3 
  template:
    spec:
      containers:
        - name: modelfit-cont-designb-t1000-p36
          image: jaccusaurelius/vu-msc-thesis:workspace
          command: ["bash", "scripts/model_fit_montecarlo.sh", "designB_T1000_p36", "fullcv"]
          resources: 
            requests:
              cpu: 2000m 
              memory: 1500Mi 
            limits:
              # cpu: 2200m
              # memory: 1500Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/out
            - name: pv-data
              mountPath: /app/vu-msc-thesis/data
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out
        - name: pv-data
          persistentVolumeClaim:
            claimName: pvc-data