apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
  - name: debian
    image: debian:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: shared-pv-out
      mountPath: /app/vu-msc-thesis/out
  volumes:
    - name: shared-pv-out
      persistentVolumeClaim:
        claimName: shared-pvc-out