apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
  - name: dataaccess-cont
    image: jaccusaurelius/vu-msc-thesis:kube
    # command: ['sh', '-c', 'rm -rf /app/vu-msc-thesis/out/simulation/lambdas && sleep infinity']
    command: ["sleep",  "infinity"]
    volumeMounts:
    - name: pv-out
      mountPath: /app/vu-msc-thesis/out
  volumes:
    - name: pv-out
      persistentVolumeClaim:
        claimName: pvc-out