apiVersion: batch/v1
kind: Job
metadata:
  name: detlam-designa-t500-p16
spec:
  completions: 50
  parallelism: 6
  template:
    spec:
      containers:
        - name: detlam-cont-designa-t500-p16
          image: jaccusaurelius/vu-msc-thesis:workspace
          command: ["bash", "scripts/determine_lambda_preliminary.sh", "designA_T500_p16"]
          resources: 
            requests:
              cpu: 1000m 
              memory: 1000Mi 
            limits:
              cpu: 1000m
              memory: 1500Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/out
            - name: pv-data
              mountPath: /app/vu-msc-thesis/data
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out
        - name: pv-data
          persistentVolumeClaim:
            claimName: pvc-data
