apiVersion: batch/v1
kind: Job
metadata:
  name: detlam-designB_T2000_p49
spec:
  completions: 20
  parallelism: 4
  template:
    spec:
      containers:
        - name: detlam-cont-designB_T2000_p49
          image: jaccusaurelius/vu-msc-thesis:workspace
          command: ["bash", "scripts/determine_lambda_preliminary.sh", "designB_T2000_p49"]
          resources: 
            requests:
              cpu: 1500m 
              memory: 1500Mi 
            limits:
              cpu: 1500m
              memory: 1900Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/outa
            - name: pv-data
              mountPath: /app/vu-msc-thesis/data
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out
        - name: pv-data
          persistentVolumeClaim:
            claimName: pvc-data
