apiVersion: batch/v1
kind: Job
metadata:
  name: detlam
spec:
  completions: 20
  parallelism: 4
  template:
    spec:
      containers:
        - name: detlam-cont
          image: jaccusaurelius/vu-msc-thesis:kube
          command: ["bash", "scripts/determine_lambda_preliminary.sh", "REPLACEME"]
          resources: 
            requests:
              cpu: 1500m 
              memory: 1500Mi 
            limits:
              cpu: 1500m
              memory: 1900Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/out
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out
