apiVersion: batch/v1
kind: Job
metadata:
  name: modelfit
spec:
  completions: 100 
  parallelism: 10
  template:
    spec:
      containers:
      - name: modelfit-cont
        image: jaccusaurelius/vu-msc-thesis:kube
        command: ["bash", "-c", "scripts/model_fit_montecarlo.sh designB_T500_p16"]
        volumeMounts:
        - name: pv-out
          mountPath: /app/vu-msc-thesis/out
      restartPolicy: Never
      volumes:
      - name: pv-out
        persistentVolumeClaim:
          claimName: pvc-out