apiVersion: batch/v1
kind: Job
metadata:
  name: modelfit-designb-t2000-p49
spec:
  completions: 100 
  parallelism: 6
  template:
    spec:
      containers:
        - name: modelfit-cont-designb-t2000-p49
          image: jaccusaurelius/vu-msc-thesis:workspace
          command: ["bash", "scripts/model_fit_montecarlo.sh", "designB_T2000_p49"]
          resources: 
            requests:
              cpu: 1000m 
              memory: 1000Mi 
            limits:
              cpu: 1000m
              memory: 1500Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/out
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out