apiVersion: batch/v1
kind: Job
metadata:
  name: modelfit
spec:
  completions: 250 
  parallelism: 4 
  template:
    spec:
      containers:
        - name: modelfit-cont
          image: jaccusaurelius/vu-msc-thesis:kube
          command: ["bash", "scripts/model_fit_montecarlo.sh", "designB_T1000_p25"]
          resources: 
            requests:
              cpu: 1500m 
              memory: 1500Mi 
            limits:
              cpu: 1500m
              memory: 1900Mi 
          volumeMounts:
            - name: pv-out
              mountPath: /app/vu-msc-thesis/outa
            - name: pv-data
              mountPath: /app/vu-msc-thesis/data
      restartPolicy: Never
      volumes:
        - name: pv-out
          persistentVolumeClaim:
            claimName: pvc-out
        - name: pv-data
          persistentVolumeClaim:
            claimName: pvc-data