apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-out
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual
  hostPath:
    path: /Users/jacco/Documents/repos/vu-msc-thesis/out
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-out
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: Pod
metadata:
  name: data-access
spec:
  containers:
  - name: data-access-cont
    image: jaccusaurelius/vu-msc-thesis:kube
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: pv-out
      mountPath: /app/vu-msc-thesis/out
  volumes:
    - name: pv-out
      persistentVolumeClaim:
        claimName: pvc-out