apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-out
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /Users/jacco/Documents/repos/vu-msc-thesis/out
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-out
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual