apiVersion: v1
kind: Pod
metadata:
  name: data-access
spec:
  containers:
  - name: data-access-cont
    image: jaccusaurelius/vu-msc-thesis:workspace
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: pv-out
      mountPath: /app/vu-msc-thesis/out
  volumes:
    - name: pv-out
      persistentVolumeClaim:
        claimName: pvc-out