apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-out
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-out
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: data-access-nfs
spec:
  containers:
  - name: data-access-nfs-container
    image: eu.gcr.io/vu-msc-thesis/vu-msc-thesis:gke
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: 500m 
        memory: 500Mi
    volumeMounts:
    - name: pv-out
      mountPath: /app/vu-msc-thesis/out
  volumes:
    - name: pv-out
      persistentVolumeClaim:
        claimName: pvc-out